name             'confies'
maintainer       'Jake Champlin'
maintainer_email 'jake.champlin.27@gmail.com'
license          'All rights reserved'
description      'Installs/Configures confies'
long_description 'Installs/Configures confies'
version          '0.1.3'

depends 'pacman'
depends 'oh-my-zsh', '~> 0.4.3'
depends 'sudo'
